var classes = [
    {
        "name": "Shopware\\WebInstaller\\Listener\\InstallerLocaleListener",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "detectLanguage",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Event\\RequestEvent",
            "Symfony\\Component\\HttpFoundation\\Request"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 77,
        "vocabulary": 22,
        "volume": 343.38,
        "difficulty": 6.89,
        "effort": 2365.48,
        "level": 0.15,
        "bugs": 0.11,
        "time": 131,
        "intelligentContent": 49.84,
        "number_operators": 15,
        "number_operands": 62,
        "number_operators_unique": 4,
        "number_operands_unique": 18,
        "cloc": 11,
        "loc": 45,
        "lloc": 34,
        "mi": 82.56,
        "mIwoC": 47.9,
        "commentWeight": 34.66,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 49.63,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 1.25,
        "totalSystemComplexity": 99.25,
        "package": "Shopware\\WebInstaller\\Listener\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Listener\\PhpConfigForcerListener",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\Routing\\RouterInterface",
            "Symfony\\Component\\HttpKernel\\Event\\RequestEvent",
            "Symfony\\Component\\HttpFoundation\\RedirectResponse"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 18,
        "vocabulary": 13,
        "volume": 66.61,
        "difficulty": 3.11,
        "effort": 207.22,
        "level": 0.32,
        "bugs": 0.02,
        "time": 12,
        "intelligentContent": 21.41,
        "number_operators": 4,
        "number_operands": 14,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 5,
        "loc": 20,
        "lloc": 15,
        "mi": 96.14,
        "mIwoC": 61.17,
        "commentWeight": 34.97,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.57,
        "totalSystemComplexity": 72.57,
        "package": "Shopware\\WebInstaller\\Listener\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\InstallerException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "cannotFindShopwareInstallation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cannotFindComposerLock",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cannotFindShopwareInComposerLock",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "RuntimeException"
        ],
        "parents": [
            "RuntimeException"
        ],
        "implements": [],
        "lcom": 3,
        "length": 7,
        "vocabulary": 5,
        "volume": 16.25,
        "difficulty": 0.5,
        "effort": 8.13,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 32.51,
        "number_operators": 3,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 4,
        "loc": 20,
        "lloc": 16,
        "mi": 97.06,
        "mIwoC": 65.12,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 9,
        "package": "Shopware\\WebInstaller\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Controller\\UpdateController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "migrateTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resetConfig",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prepare",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "finish",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "patchSymfonyFlex",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLatestVersions",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Shopware\\WebInstaller\\Services\\RecoveryManager",
            "Shopware\\WebInstaller\\Services\\ReleaseInfoProvider",
            "Shopware\\WebInstaller\\Services\\FlexMigrator",
            "Shopware\\WebInstaller\\Services\\StreamedCommandResponseGenerator",
            "Shopware\\WebInstaller\\Services\\ProjectComposerJsonUpdater",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Shopware\\WebInstaller\\Services\\FileBackup",
            "Shopware\\WebInstaller\\Services\\CleanupFiles",
            "Shopware\\WebInstaller\\Services\\PluginCompatibility",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Request"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 2,
        "length": 219,
        "vocabulary": 69,
        "volume": 1337.77,
        "difficulty": 7.03,
        "effort": 9406.17,
        "level": 0.14,
        "bugs": 0.45,
        "time": 523,
        "intelligentContent": 190.26,
        "number_operators": 39,
        "number_operands": 180,
        "number_operators_unique": 5,
        "number_operands_unique": 64,
        "cloc": 16,
        "loc": 101,
        "lloc": 85,
        "mi": 64.13,
        "mIwoC": 35.21,
        "commentWeight": 28.91,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 625,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 625.44,
        "totalStructuralComplexity": 5625,
        "totalDataComplexity": 3.92,
        "totalSystemComplexity": 5628.92,
        "package": "Shopware\\WebInstaller\\Controller\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Controller\\PhpConfigController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Shopware\\WebInstaller\\Services\\PhpBinaryFinder",
            "Shopware\\WebInstaller\\Services\\RecoveryManager",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 2,
        "length": 40,
        "vocabulary": 21,
        "volume": 175.69,
        "difficulty": 5,
        "effort": 878.46,
        "level": 0.2,
        "bugs": 0.06,
        "time": 49,
        "intelligentContent": 35.14,
        "number_operators": 8,
        "number_operands": 32,
        "number_operators_unique": 5,
        "number_operands_unique": 16,
        "cloc": 6,
        "loc": 27,
        "lloc": 21,
        "mi": 88.26,
        "mIwoC": 54.9,
        "commentWeight": 33.35,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.39,
        "relativeSystemComplexity": 64.39,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0.78,
        "totalSystemComplexity": 128.78,
        "package": "Shopware\\WebInstaller\\Controller\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Controller\\IndexController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 8,
        "vocabulary": 8,
        "volume": 24,
        "difficulty": 0.5,
        "effort": 12,
        "level": 2,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 48,
        "number_operators": 1,
        "number_operands": 7,
        "number_operators_unique": 1,
        "number_operands_unique": 7,
        "cloc": 5,
        "loc": 13,
        "lloc": 8,
        "mi": 111.48,
        "mIwoC": 70.5,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "Shopware\\WebInstaller\\Controller\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Controller\\InstallController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cleanup",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Shopware\\WebInstaller\\Services\\RecoveryManager",
            "Shopware\\WebInstaller\\Services\\StreamedCommandResponseGenerator",
            "Shopware\\WebInstaller\\Services\\ReleaseInfoProvider",
            "Shopware\\WebInstaller\\Services\\ProjectComposerJsonUpdater",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\StreamedResponse",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Filesystem\\Filesystem",
            "Symfony\\Component\\HttpFoundation\\StreamedResponse",
            "Symfony\\Component\\Filesystem\\Filesystem"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 2,
        "length": 112,
        "vocabulary": 51,
        "volume": 635.31,
        "difficulty": 3.79,
        "effort": 2406.07,
        "level": 0.26,
        "bugs": 0.21,
        "time": 134,
        "intelligentContent": 167.75,
        "number_operators": 23,
        "number_operands": 89,
        "number_operators_unique": 4,
        "number_operands_unique": 47,
        "cloc": 12,
        "loc": 58,
        "lloc": 46,
        "mi": 76.09,
        "mIwoC": 43.7,
        "commentWeight": 32.39,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 196.22,
        "totalStructuralComplexity": 784,
        "totalDataComplexity": 0.87,
        "totalSystemComplexity": 784.87,
        "package": "Shopware\\WebInstaller\\Controller\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Controller\\FinishController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "default",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Filesystem\\Filesystem"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController"
        ],
        "implements": [],
        "lcom": 1,
        "length": 38,
        "vocabulary": 24,
        "volume": 174.23,
        "difficulty": 3.68,
        "effort": 641.89,
        "level": 0.27,
        "bugs": 0.06,
        "time": 36,
        "intelligentContent": 47.29,
        "number_operators": 10,
        "number_operands": 28,
        "number_operators_unique": 5,
        "number_operands_unique": 19,
        "cloc": 10,
        "loc": 31,
        "lloc": 22,
        "mi": 93.15,
        "mIwoC": 54.62,
        "commentWeight": 38.53,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 49.38,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.38,
        "totalSystemComplexity": 49.38,
        "package": "Shopware\\WebInstaller\\Controller\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Services\\ProjectComposerJsonUpdater",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getVersion",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureRepositories",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getConflictMinVersion",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 17,
        "ccn": 13,
        "ccnMethodMax": 6,
        "externals": [
            "Symfony\\Contracts\\HttpClient\\HttpClientInterface",
            "Composer\\Util\\Platform",
            "Composer\\Util\\Platform",
            "Composer\\Util\\Platform",
            "Composer\\Semver\\VersionParser"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 150,
        "vocabulary": 53,
        "volume": 859.19,
        "difficulty": 8.07,
        "effort": 6929.54,
        "level": 0.12,
        "bugs": 0.29,
        "time": 385,
        "intelligentContent": 106.53,
        "number_operators": 44,
        "number_operands": 106,
        "number_operators_unique": 7,
        "number_operands_unique": 46,
        "cloc": 13,
        "loc": 87,
        "lloc": 74,
        "mi": 65.12,
        "mIwoC": 36.93,
        "commentWeight": 28.18,
        "kanDefect": 1.24,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.82,
        "relativeSystemComplexity": 81.82,
        "totalStructuralComplexity": 405,
        "totalDataComplexity": 4.1,
        "totalSystemComplexity": 409.1,
        "package": "Shopware\\WebInstaller\\Services\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Services\\FlexMigrator",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "cleanup",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "patchRootComposerJson",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "copyNewTemplateFiles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "migrateEnvFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addSymlinkRepository",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 11,
        "ccnMethodMax": 5,
        "externals": [
            "Symfony\\Component\\Filesystem\\Filesystem",
            "Symfony\\Component\\Filesystem\\Filesystem"
        ],
        "parents": [],
        "implements": [],
        "lcom": 4,
        "length": 193,
        "vocabulary": 78,
        "volume": 1213.08,
        "difficulty": 5.21,
        "effort": 6314.68,
        "level": 0.19,
        "bugs": 0.4,
        "time": 351,
        "intelligentContent": 233.04,
        "number_operators": 41,
        "number_operands": 152,
        "number_operators_unique": 5,
        "number_operands_unique": 73,
        "cloc": 47,
        "loc": 127,
        "lloc": 87,
        "mi": 75.07,
        "mIwoC": 34.62,
        "commentWeight": 40.45,
        "kanDefect": 1.17,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 127.5,
        "package": "Shopware\\WebInstaller\\Services\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Services\\FileBackup",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "restore",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "backup",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Filesystem\\Filesystem",
            "Symfony\\Component\\Filesystem\\Filesystem"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 23,
        "vocabulary": 7,
        "volume": 64.57,
        "difficulty": 3.6,
        "effort": 232.45,
        "level": 0.28,
        "bugs": 0.02,
        "time": 13,
        "intelligentContent": 17.94,
        "number_operators": 5,
        "number_operands": 18,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 4,
        "loc": 26,
        "lloc": 22,
        "mi": 86.32,
        "mIwoC": 57.77,
        "commentWeight": 28.55,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 9.13,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 36.5,
        "package": "Shopware\\WebInstaller\\Services\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Services\\PhpBinaryFinder",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "find",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findHostedSpecificBinary",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPhpVersionPath",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isPHPRunning",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 9,
        "ccnMethodMax": 6,
        "externals": [
            "Symfony\\Component\\Process\\ExecutableFinder",
            "Symfony\\Component\\Process\\Process"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 107,
        "vocabulary": 65,
        "volume": 644.39,
        "difficulty": 4.12,
        "effort": 2654.03,
        "level": 0.24,
        "bugs": 0.21,
        "time": 147,
        "intelligentContent": 156.46,
        "number_operators": 26,
        "number_operands": 81,
        "number_operators_unique": 6,
        "number_operands_unique": 59,
        "cloc": 9,
        "loc": 61,
        "lloc": 52,
        "mi": 69.71,
        "mIwoC": 41.69,
        "commentWeight": 28.03,
        "kanDefect": 0.96,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1.36,
        "relativeSystemComplexity": 37.36,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 5.43,
        "totalSystemComplexity": 149.43,
        "package": "Shopware\\WebInstaller\\Services\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Services\\ReleaseInfoProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchVersions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchUpdateVersions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMajor",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNextMajor",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 7,
        "ccnMethodMax": 6,
        "externals": [
            "Symfony\\Component\\HttpClient\\HttpClient",
            "Composer\\Util\\Platform"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 98,
        "vocabulary": 27,
        "volume": 465.98,
        "difficulty": 8.07,
        "effort": 3759.6,
        "level": 0.12,
        "bugs": 0.16,
        "time": 209,
        "intelligentContent": 57.76,
        "number_operators": 27,
        "number_operands": 71,
        "number_operators_unique": 5,
        "number_operands_unique": 22,
        "cloc": 13,
        "loc": 62,
        "lloc": 49,
        "mi": 76.07,
        "mIwoC": 43.5,
        "commentWeight": 32.57,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 1.1,
        "relativeSystemComplexity": 50.1,
        "totalStructuralComplexity": 245,
        "totalDataComplexity": 5.5,
        "totalSystemComplexity": 250.5,
        "package": "Shopware\\WebInstaller\\Services\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Services\\RecoveryManager",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getBinary",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPHPBinary",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProjectDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getShopwareLocation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCurrentShopwareVersion",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isFlexProject",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 10,
        "ccnMethodMax": 6,
        "externals": [
            "Symfony\\Component\\HttpFoundation\\Request",
            "Shopware\\WebInstaller\\InstallerException",
            "Shopware\\WebInstaller\\InstallerException",
            "Shopware\\WebInstaller\\InstallerException",
            "Shopware\\WebInstaller\\InstallerException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 5,
        "length": 89,
        "vocabulary": 31,
        "volume": 440.92,
        "difficulty": 8.75,
        "effort": 3858.08,
        "level": 0.11,
        "bugs": 0.15,
        "time": 214,
        "intelligentContent": 50.39,
        "number_operators": 29,
        "number_operands": 60,
        "number_operators_unique": 7,
        "number_operands_unique": 24,
        "cloc": 8,
        "loc": 64,
        "lloc": 56,
        "mi": 68.04,
        "mIwoC": 42,
        "commentWeight": 26.04,
        "kanDefect": 0.96,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.3,
        "relativeSystemComplexity": 17.3,
        "totalStructuralComplexity": 96,
        "totalDataComplexity": 7.8,
        "totalSystemComplexity": 103.8,
        "package": "Shopware\\WebInstaller\\Services\\",
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Services\\PluginCompatibility",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeIncompatible",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getInstalledPackagesByType",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getInstallPath",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRequires",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isPluginCompatible",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 20,
        "ccn": 15,
        "ccnMethodMax": 5,
        "externals": [
            "Composer\\Semver\\Semver"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 140,
        "vocabulary": 45,
        "volume": 768.86,
        "difficulty": 9.3,
        "effort": 7152.42,
        "level": 0.11,
        "bugs": 0.26,
        "time": 397,
        "intelligentContent": 82.65,
        "number_operators": 39,
        "number_operands": 101,
        "number_operators_unique": 7,
        "number_operands_unique": 38,
        "cloc": 29,
        "loc": 102,
        "lloc": 73,
        "mi": 73.89,
        "mIwoC": 37.13,
        "commentWeight": 36.76,
        "kanDefect": 1.4,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.69,
        "relativeSystemComplexity": 26.69,
        "totalStructuralComplexity": 150,
        "totalDataComplexity": 10.17,
        "totalSystemComplexity": 160.17,
        "package": "Shopware\\WebInstaller\\Services\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Services\\StreamedCommandResponseGenerator",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "runJSON",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\HttpFoundation\\StreamedResponse",
            "Symfony\\Component\\Process\\Process",
            "Symfony\\Component\\HttpFoundation\\StreamedResponse",
            "Symfony\\Component\\HttpFoundation\\StreamedResponse"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 36,
        "vocabulary": 15,
        "volume": 140.65,
        "difficulty": 7.5,
        "effort": 1054.86,
        "level": 0.13,
        "bugs": 0.05,
        "time": 59,
        "intelligentContent": 18.75,
        "number_operators": 6,
        "number_operands": 30,
        "number_operators_unique": 5,
        "number_operands_unique": 10,
        "cloc": 11,
        "loc": 39,
        "lloc": 28,
        "mi": 89.64,
        "mIwoC": 52.99,
        "commentWeight": 36.65,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.57,
        "relativeSystemComplexity": 36.57,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.14,
        "totalSystemComplexity": 73.14,
        "package": "Shopware\\WebInstaller\\Services\\",
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Services\\CleanupFiles",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "cleanup",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Component\\Filesystem\\Filesystem",
            "Symfony\\Component\\Filesystem\\Path"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 68,
        "vocabulary": 56,
        "volume": 394.9,
        "difficulty": 1.17,
        "effort": 460.72,
        "level": 0.86,
        "bugs": 0.13,
        "time": 26,
        "intelligentContent": 338.49,
        "number_operators": 5,
        "number_operands": 63,
        "number_operators_unique": 2,
        "number_operands_unique": 54,
        "cloc": 19,
        "loc": 54,
        "lloc": 35,
        "mi": 87.35,
        "mIwoC": 47.6,
        "commentWeight": 39.75,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 9.25,
        "package": "Shopware\\WebInstaller\\Services\\",
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Shopware\\WebInstaller\\Kernel",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "registerBundles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProjectDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLogDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCacheDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureContainer",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "configureRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Component\\HttpKernel\\Kernel",
            "Symfony\\Bundle\\FrameworkBundle\\FrameworkBundle",
            "Symfony\\Bundle\\TwigBundle\\TwigBundle",
            "Symfony\\Component\\DependencyInjection\\ContainerBuilder",
            "Symfony\\Component\\Config\\Loader\\LoaderInterface",
            "Symfony\\Component\\Routing\\Loader\\Configurator\\RoutingConfigurator"
        ],
        "parents": [
            "Symfony\\Component\\HttpKernel\\Kernel"
        ],
        "implements": [],
        "lcom": 5,
        "length": 24,
        "vocabulary": 12,
        "volume": 86.04,
        "difficulty": 1.5,
        "effort": 129.06,
        "level": 0.67,
        "bugs": 0.03,
        "time": 7,
        "intelligentContent": 57.36,
        "number_operators": 9,
        "number_operands": 15,
        "number_operators_unique": 2,
        "number_operands_unique": 10,
        "cloc": 7,
        "loc": 36,
        "lloc": 29,
        "mi": 85.98,
        "mIwoC": 54.42,
        "commentWeight": 31.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.13,
        "relativeSystemComplexity": 10.13,
        "totalStructuralComplexity": 54,
        "totalDataComplexity": 6.75,
        "totalSystemComplexity": 60.75,
        "package": "Shopware\\WebInstaller\\",
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    }
]